name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build solver
      run: cmake ${{github.workspace}}/solver_application/ -B ${{github.workspace}}/solver_application/build

    - name: Run solver
      run: cmake --build ${{github.workspace}}/solver_application/build
      
    - name: Build hello_world
      run: cmake ${{github.workspace}}/hello_world_application/ -B ${{github.workspace}}/hello_world_application/build
      
    - name: Run hello_world
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/hello_world_application/build

